### ISSUE TITLE
battledisplay failing on old linux dev machine

### ISSUE THREAD

**Issue by misterunix** [misterunix/basicbots#9]
Version v0.0.1a

Linux newdev.localdomain 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.9.2009 (Core)

```./basicbots64 -b  robots/rook.bas robots/corner-runner.bas
panic: close of nil channel

goroutine 1 [running]:
github.com/gdamore/tcell/v2.(*tScreen).finish(...)
        /home/bjones/go/pkg/mod/github.com/gdamore/tcell/v2@v2.4.0/tscreen.go:481
sync.(*Once).doSlow(0xc0001aa0c0, 0xc0001c8000)
        /usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/gdamore/tcell/v2.(*tScreen).Fini(0xc000054180)
        /home/bjones/go/pkg/mod/github.com/gdamore/tcell/v2@v2.4.0/tscreen.go:477 +0x47
main.main()
        /home/bjones/go/src/basicbots/main.go:70 +0x463
```
Line reported is: `scr.Fini()`
BUT there is more to it than that. The battlescreen never displays. 
Tried compiling on both linux boxes and the Cento fails.

---

works on
Linux Dev1 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.04.3 LTS

**Comment by misterunix** [comment]
opps forgot bug tag.
